server:
  port: 8062
#应用名称（nacos会将该名称作为服务的名称注册）
spring:
  application:
    name: hyxtrix-demo
    #配置nacos地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        #nacos的默认账号密码即使nacos
        username: nacos
        password: nacos
        #命名空间可以用来将服务隔离在各个不同的空间中方便管理
        #例如可以格利城dev fat等
        namespace: public
        ephemeral: true
#让hystrix起效
feign:
  hystrix:
    enabled: true


